home-assistant:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # hajimari.io/appName: Paperless
        # hajimari.io/icon: file-document
      hosts:
        - host: &host hass.home.hendricksen.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
  postgresql:
    enabled: true
